export const CLEAR_ALL_PATIENTS = 'CLEAR_ALL_PATIENTS';
export const GET_PATIENTS_DATA_STARTING = 'GET_PATIENTS_DATA_STARTING';
export const GET_PATIENTS_DATA_SUCCESS = 'GET_PATIENTS_DATA_SUCCESS';
export const GET_PATIENTS_DATA_ERROR = 'GET_PATIENTS_DATA_ERROR';

export const CLEAR_ALL_REPORTS = 'CLEAR_ALL_REPORTS';
export const GET_REPORTS_DATA_STARTING = 'GET_REPORTS_DATA_STARTING';
export const GET_REPORTS_DATA_SUCCESS = 'GET_REPORTS_DATA_SUCCESS';
export const GET_REPORTS_DATA_ERROR = 'GET_REPORTS_DATA_ERROR';

export const CLEAR_ALL_HELP_REQUESTS = 'CLEAR_ALL_HELP_REQUESTS';
export const GET_HELP_REQUESTS_STARTING = 'GET_HELP_REQUESTS_STARTING';
export const GET_HELP_REQUESTS_SUCCESS = 'GET_HELP_REQUESTS_SUCCESS';
export const GET_HELP_REQUESTS_ERROR = 'GET_HELP_REQUESTS_ERROR';

export const SEND_REPORT_STARTING = 'SEND_REPORT_STARTING';
export const SEND_REPORT_SUCCESS = 'SEND_REPORT_SUCCESS';
export const SEND_REPORT_ERROR = 'SEND_REPORT_ERROR';

export const SEND_REQUEST_HELP_STARTING = 'SEND_REQUEST_HELP_STARTING';
export const SEND_REQUEST_HELP_SUCCESS = 'SEND_REQUEST_HELP_SUCCESS';
export const SEND_REQUEST_HELP_ERROR = 'SEND_REQUEST_HELP_ERROR';

export const SET_LANGUAGE = 'SET_LANGUAGE';
