export const GET_PATIENTS_DATA_STARTING = 'GET_PATIENTS_DATA_STARTING';
export const GET_PATIENTS_DATA_SUCCESS = 'GET_PATIENTS_DATA_SUCCESS';
export const GET_PATIENTS_DATA_ERROR = 'GET_PATIENTS_DATA_ERROR';

export const GET_REPORTS_DATA_STARTING = 'GET_REPORTS_DATA_STARTING';
export const GET_REPORTS_DATA_SUCCESS = 'GET_REPORTS_DATA_SUCCESS';
export const GET_REPORTS_DATA_ERROR = 'GET_REPORTS_DATA_ERROR';
