export const GET_PATIENTS_DATA_STARTING = 'GET_PATIENTS_DATA_STARTING';
export const GET_PATIENTS_DATA_SUCCESS = 'GET_PATIENTS_DATA_SUCCESS';
export const GET_PATIENTS_DATA_ERROR = 'GET_PATIENTS_DATA_ERROR';

export const GET_REPORTS_DATA_STARTING = 'GET_REPORTS_DATA_STARTING';
export const GET_REPORTS_DATA_SUCCESS = 'GET_REPORTS_DATA_SUCCESS';
export const GET_REPORTS_DATA_ERROR = 'GET_REPORTS_DATA_ERROR';

export const SEND_REPORT_STARTING = 'SEND_REPORT_STARTING';
export const SEND_REPORT_SUCCESS = 'SEND_REPORT_SUCCESS';
export const SEND_REPORT_ERROR = 'SEND_REPORT_ERROR';

export const SEND_REQUEST_HELP_STARTING = 'SEND_REQUEST_HELP_STARTING';
export const SEND_REQUEST_HELP_SUCCESS = 'SEND_REQUEST_HELP_SUCCESS';
export const SEND_REQUEST_HELP_ERROR = 'SEND_REQUEST_HELP_ERROR';
